#!/usr/bin/env python3
"""
Fully Autonomous LinkedIn Poster
- Generates posts automatically
- Posts to LinkedIn automatically
- No manual approval needed
- Runs 24/7
"""

import sys
sys.stdout.reconfigure(encoding='utf-8')

import os
import time
from datetime import datetime, timedelta
from pathlib import Path
from dotenv import load_dotenv
import random

try:
    from linkedin_auto_poster import LinkedInPoster
    LINKEDIN_AVAILABLE = True
except:
    LINKEDIN_AVAILABLE = False
    print("⚠️ LinkedIn poster not available")

load_dotenv()


class FullyAutonomousLinkedIn:
    """Fully automatic LinkedIn posting system"""
    
    def __init__(self):
        self.post_interval = 21600  # 6 hours in seconds
        self.last_post_time = None
        self.posted_folder = Path('03_Posted/History')
        self.posted_folder.mkdir(parents=True, exist_ok=True)
        
        # Post templates for automatic generation
        self.post_templates = [
            "🚀 Excited to share insights on AI and automation! The future of work is here. #AI #Automation #Innovation",
            "💡 Just learned something amazing about machine learning today. Technology never stops evolving! #MachineLearning #Tech",
            "🌟 Building the future, one line of code at a time. What are you working on today? #Coding #Development",
            "📊 Data-driven decisions lead to better outcomes. Always measure, always improve. #DataScience #Analytics",
            "🤖 Automation is not about replacing humans, it's about empowering them. #Automation #Future",
            "💻 Clean code is not just about functionality, it's about maintainability. #CleanCode #BestPractices",
            "🎯 Setting goals is important, but taking action is what makes the difference. #Productivity #Goals",
            "🔧 Every problem is an opportunity to learn something new. Keep building! #Learning #Growth",
            "🌐 The best way to predict the future is to create it. What are you creating? #Innovation #Tech",
            "⚡ Speed matters, but quality matters more. Build things that last. #Quality #Engineering"
        ]
    
    def generate_post(self):
        """Generate a new LinkedIn post"""
        try:
            # Select random template
            content = random.choice(self.post_templates)
            
            # Add timestamp
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            
            # Create filename
            filename = f"LinkedIn_Post_{timestamp}.md"
            filepath = self.posted_folder / filename
            
            # Create post file
            post_content = f"""---
platform: LinkedIn
created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
status: auto-generated
---

## Content

{content}

---
*Auto-generated by Fully Autonomous System*
"""
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(post_content)
            
            print(f"✅ Generated post: {filename}")
            return filepath
            
        except Exception as e:
            print(f"❌ Error generating post: {e}")
            return None
    
    def post_to_linkedin(self, filepath):
        """Post to LinkedIn using browser automation with error handling"""
        if not LINKEDIN_AVAILABLE:
            print("❌ LinkedIn poster not available")
            return False
        
        poster = None
        try:
            print(f"\n📤 Posting to LinkedIn: {filepath.name}")
            
            poster = LinkedInPoster(headless=False)
            poster.setup_driver()
            
            if not poster.login():
                print("❌ Login failed")
                return False
            
            if poster.post_from_file(str(filepath)):
                print("✅ Posted successfully!")
                
                new_name = f"POSTED_{filepath.name}"
                new_path = filepath.parent / new_name
                filepath.rename(new_path)
                print(f"✅ Renamed to: {new_name}")
                
                return True
            else:
                print("❌ Failed to post")
                return False
                
        except Exception as e:
            print(f"❌ Error posting: {e}")
            return False
            
        finally:
            if poster:
                try:
                    time.sleep(3)
                    poster.close()
                except:
                    pass
    
    def should_post(self):
        """Check if it's time to post"""
        if not self.last_post_time:
            return True
        
        time_diff = datetime.now() - self.last_post_time
        return time_diff.total_seconds() >= self.post_interval
    
    def run(self):
        """Main autonomous loop"""
        print("=" * 60)
        print("🤖 FULLY AUTONOMOUS LINKEDIN POSTER")
        print("=" * 60)
        print()
        print("⚡ Mode: Fully Automatic")
        print(f"⏰ Post Interval: {self.post_interval // 3600} hours")
        print("🔄 No manual approval needed")
        print()
        print("Press Ctrl+C to stop")
        print("=" * 60)
        print()
        
        iteration = 0
        
        while True:
            try:
                iteration += 1
                timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                
                print(f"\n🔄 Iteration #{iteration} - {timestamp}")
                print("-" * 60)
                
                if self.should_post():
                    print("📝 Time to create and post!")
                    
                    try:
                        filepath = self.generate_post()
                        
                        if filepath:
                            time.sleep(5)
                            
                            success = self.post_to_linkedin(filepath)
                            
                            if success:
                                self.last_post_time = datetime.now()
                                print(f"✅ Post successful!")
                                print(f"⏰ Next post in {self.post_interval // 3600} hours")
                            else:
                                print("❌ Post failed, will retry next iteration")
                    except Exception as e:
                        print(f"❌ Error in post cycle: {e}")
                        print("🔄 Will retry next iteration")
                
                else:
                    # Calculate time until next post
                    time_until_next = self.post_interval - (datetime.now() - self.last_post_time).total_seconds()
                    hours = int(time_until_next // 3600)
                    minutes = int((time_until_next % 3600) // 60)
                    
                    print(f"⏳ Next post in: {hours}h {minutes}m")
                
                print(f"✅ Iteration #{iteration} complete")
                print(f"😴 Sleeping for 15 minutes...")
                
                # Sleep for 15 minutes before next check
                time.sleep(900)
                
            except KeyboardInterrupt:
                print("\n\n🛑 Stopping Autonomous System...")
                print("✅ Shutdown complete")
                break
                
            except Exception as e:
                print(f"❌ Error in loop: {e}")
                print("🔄 Continuing in 60 seconds...")
                time.sleep(60)


def main():
    """Start fully autonomous system"""
    system = FullyAutonomousLinkedIn()
    system.run()


if __name__ == "__main__":
    main()
