#!/usr/bin/env python3
"""
Silver Tier - Daily Odoo Sync
Automated daily synchronization with Odoo system
"""

import os
import sys
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Add current directory to path for imports
sys.path.append(str(Path(__file__).parent))

try:
    from odoo_integration_example import OdooClient
    ODOO_AVAILABLE = True
except ImportError:
    ODOO_AVAILABLE = False

def log_sync_event(message, level="INFO"):
    """Log sync events"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_file = Path("logs/odoo_sync.log")
    log_file.parent.mkdir(exist_ok=True)
    
    with open(log_file, 'a', encoding='utf-8') as f:
        f.write(f"[{timestamp}] [{level}] {message}\n")
    
    print(f"[{timestamp}] [{level}] {message}")

def update_dashboard():
    """Update dashboard with latest Odoo data"""
    if not ODOO_AVAILABLE:
        log_sync_event("Odoo client not available", "WARNING")
        return False
    
    try:
        log_sync_event("Starting daily Odoo sync...")
        
        # Connect to Odoo
        client = OdooClient()
        client.authenticate()
        log_sync_event("Connected to Odoo successfully")
        
        # Get accounting summary
        summary = client.get_accounting_summary()
        log_sync_event(f"Retrieved accounting data: {summary['customers']['total']} customers, {summary['invoices']['total']} invoices")
        
        # Update Dashboard.md
        dashboard_content = f"""
# 📊 Daily Odoo Sync - {datetime.now().strftime('%Y-%m-%d')}

## Accounting Summary

### Customers
- **Total Customers**: {summary['customers']['total']}
- **Active Customers**: {summary['customers']['active']}

### Invoices
- **Total Invoices**: {summary['invoices']['total']}
- **Unpaid Invoices**: {summary['invoices']['unpaid_count']}
- **Unpaid Amount**: ${summary['invoices']['unpaid_amount']:.2f}

### Key Metrics
- **Collection Rate**: {((summary['invoices']['total'] - summary['invoices']['unpaid_count']) / max(summary['invoices']['total'], 1) * 100):.1f}%
- **Average Invoice Value**: ${(summary['invoices']['unpaid_amount'] / max(summary['invoices']['unpaid_count'], 1)):.2f}

---
*Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} (Automated Daily Sync)*
"""
        
        # Write to dashboard
        dashboard_file = Path("AI_Employee_Vault/Dashboard.md")
        with open(dashboard_file, 'w', encoding='utf-8') as f:
            f.write(dashboard_content)
        
        log_sync_event("Dashboard updated successfully")
        
        # Create alert for overdue invoices
        if summary['invoices']['unpaid_count'] > 0:
            alert_content = f"""
# 🚨 ALERT - Overdue Invoices

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary
- **Unpaid Invoices**: {summary['invoices']['unpaid_count']}
- **Total Amount**: ${summary['invoices']['unpaid_amount']:.2f}

## Action Required
Please review overdue invoices in Odoo and follow up with customers.

---
*Generated by Silver Tier Daily Sync*
"""
            
            alert_file = Path("00_Inbox/ALERTS.md")
            with open(alert_file, 'a', encoding='utf-8') as f:
                f.write(alert_content)
            
            log_sync_event(f"Alert created for {summary['invoices']['unpaid_count']} overdue invoices", "WARNING")
        
        return True
        
    except Exception as e:
        log_sync_event(f"Sync failed: {str(e)}", "ERROR")
        
        # Create error alert
        error_alert = f"""
# ❌ ERROR - Odoo Sync Failed

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Error**: {str(e)}

## Action Required
Check Odoo connection and credentials.

---
*Generated by Silver Tier Daily Sync*
"""
        
        alert_file = Path("00_Inbox/ALERTS.md")
        with open(alert_file, 'a', encoding='utf-8') as f:
            f.write(error_alert)
        
        return False

def main():
    """Main sync function"""
    log_sync_event("=" * 50)
    log_sync_event("SILVER TIER - DAILY ODOO SYNC")
    log_sync_event("=" * 50)
    
    success = update_dashboard()
    
    if success:
        log_sync_event("Daily sync completed successfully")
    else:
        log_sync_event("Daily sync completed with errors", "ERROR")
    
    log_sync_event("=" * 50)

if __name__ == "__main__":
    main()